package com.example.saes401.helper;

public final class GameConstant {

    public static final int DEFAULT_HP = 3;
    public static final int DEFAULT_INVENTORY_SLOT = 3;
    public static final String CATALOGUE = "catalogue";
    public static final String OBJETS = "objets";
    public static final String NIVEAU1 = "niveau1";
    public static final String NIVEAU2 = "niveau2";
    public static final String NIVEAU3 = "niveau3";
    public static final String PLAYERS_JSON = "players";
    public static final String KEY_LEVEL = "currentLevelInstance";
    public static final String KEY_PLAYER = "playerInstance";
    public static final String KEY_ENEMIE_INDEX = "currentEnemie";
    public static final String KEY_ENEMIE_INSTANCE = "currentEnemieIntance";
    public static final String KEY_INVENTORY_ENEMIE = "inventoryEnemie";
    public static final String KEY_HP_LEFT_ENEMIE = "hpLeftEnemie";
    public static final String KEY_END_FIGHT = "endFight";
    public static final String KEY_DATA_MODEL = "dataModel";
    public static final String VALUE_GAME_ACTIVITY = "gameActivity";
    public static final String VALUE_GAME_CHOISE = "gameChoise";
    public static final String VALUE_GAME_NARATION = "gameNaration";
    public static final String VALUE_MAIN_ACTIVITY = "mainActivity";
    public static final String VALUE_PLAYER_CHOISE = "playerChoise";
    public static final String VALUE_STORY = "story";
    public static final String KEY_PREVIOUS_ACTIVITY = "previousActivity";
    public static final String FORMAT_LEVEL = "niveau%d";
    public static final String FORMAT_SCORE = "score : %d";
    public static final String FORMAT_CURRENT_LEVEL = "%d - %d";
    public static final String FORMAT_HEART_ENEMIE = "heart_enemie_%d";
    public static final String FORMAT_HEART_PLAYER = "heart_player_%d";
    public static final String FORMAT_BUTTON_CHOISE = "imageButton%d";
    public static final String REGEX_SPLITER = "d";
    public static final String KEY_PLAYER_WIN = "isPlayerWin";
    public static final String KEY_START_LEVEL = "onStarLevel";
    public static final int WIDTH_HEIGHT_ITEMS = 130;
    public static final int MARGIN_ITEM = 40;
    public static final int DELAY_TIME = 3000;
    public static final String CLEE_MAUDITE_FR = "cle maudite";
    public static final String CLEE_MAUDITE_EN = "Cursed Key";
    public static final String VOLUME = "SavedVolume";
    public static final String LANGUE = "SavedLanguage";
    public static final String FORMAT_STAT_EN = "Score: %s \nDuration: %s \nMax Damage to Player: %d \nMax Damage to Enemy: %d \nHeart Lost: %d \nResult: %s";
    public static final String FORMAT_STAT_FR = "Score: %s \nDurée: %s \nDégats maximum au joueur: %d \nDégats maximum au ennemi: %d \nVie perdue: %d \nRésultat: %s";
    public static final String KEY_PAGINATION = "pageActuel";
    public static final String KEY_GAME_SAVE = "gameSave";
    public static final String CONTINUE_GAME = "continueGame";
    public static final String VALUE_GAME_CONTINUE = "gameContinue";
}
